### ISSUE TITLE
Use separate true energy axis for 3D benchmarks

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy-benchmarks#100]
I noticed that we don't specify a separate true energy axis e.g. here https://github.com/gammapy/gammapy-benchmarks/blob/master/benchmarks/analysis_3d_joint.py#L42. To get a more realistic analysis scenario and be able to assess changes like https://github.com/gammapy/gammapy/pull/3349 we should add this.

**Comment by QRemy** [comment]
https://github.com/gammapy/gammapy-benchmarks/pull/102
