### ISSUE TITLE
Location of provenance extraction

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy-benchmarks#62]
We discussed this morning about having some provenance information for each run of the validation as is currently done for benchmark. 
I assume that this is something that is the responsibility of the general `make.py`, not of each individual validation project (fermi, CTA 1DC, joint-crab etc). So it does not need to be reimplemented in each of them. Right @Bultako ?

**Comment by Bultako** [comment]
Yes @registerrier 
It is foreseen to develop a `make.py` script creating a `provenance.yaml` file for each validation process, as it is already the case for benchmarks. So, validations scripts should not worry about this.

**Comment by registerrier** [comment]
Thanks @Bultako . Then I close the issue.
